server:
  port: 8080

spring:
  datasource:
    username: root
    password: 551200
    url: jdbc:mysql://localhost:3306/myblog-leo?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    rest:
      base-path: /api
      default-page-size: 10