server:
  port: 8080

spring:
  datasource:
    username: root
    password: 551200
    url: jdbc:mysql://127.0.0.1:3306/myblog-leo?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  data:
    rest:
      base-path: /api
      default-page-size: 10
      # swagger和springboot的兼容问题
  mvc:
    path match:
      matching-strategy: ant_path_matcher


# Sa-Token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: leoeric
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 3600
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
